name: Publish package to GitHub Packages

on:
  push:
    branches: [ "main" ]  # Only publish from main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up JDK + Maven authentication
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github          # must match <id> in pom.xml
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      # 3. Build and deploy to GitHub Packages
      - name: Build & Deploy
        run: mvn -B deploy -DskipTests
