name: Maven Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # required for GitHub Packages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          server-id: github                # must match <id> in your pom.xml
          server-username: GITHUB_ACTOR    # provided automatically by Actions
          server-password: ${{ secrets.GITHUB_TOKEN }} # or use GH_PACKAGES_TOKEN if PAT is needed

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and deploy
        run: mvn -B clean deploy -DskipTests
